networks:
  rossmann-network:
    external: true

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - rossmann-network
    ports:
      - 1500:6379

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    networks:
      - rossmann-network
    ports:
      - 1501:5540

  api:
    container_name: api
    networks:
      - rossmann-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 1300:8000